// <auto-generated />
namespace Shop2.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeletePromotionPrice_OrderDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletePromotionPrice_OrderDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201903141628452_DeletePromotionPrice_OrderDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
